
tasksRoutes = FlowRouter.group
    prefix: '/tasks'


tasksRoutes.route '/',
    name: 'tasks'
    action: () ->
        BlazeLayout.render 'application',
            content: 'tasks'

tasksRoutes.route '/add',
    name: 'tasksAdd'
    action: () ->
        BlazeLayout.render 'application',
            content: 'tasksAdd'

# Meteor.subscribe('alltasks')
#
# FlowRouter.route '/blog/:title',
#   subscriptions: (params) ->
#     @register 'singlePost', Meteor.subscribe('singlePost', params.title)
#     return
#   action: (params) ->
#     FlowRouter.subsReady ->
#       Blaze.renderWithData Template.post, Posts.findOne(), mainContainer
#       return
#     return

# ---
# generated by js2coffee 2.1.0


tasksRoutes.route '/:taskId',
    name: 'tasksItem'
    #
    subscriptions: (params, queryParams) ->
        @register 'tasksItem', Meteor.subscribe('tasksItem', params.taskId)

    action: (params) ->
        FlowRouter.subsReady ->
            if task = Tasks.findOne()
                BlazeLayout.render 'application',
                    content: 'tasksItem'
                    params: task
            else
                BlazeLayout.render 'notFound'
